"""add columns to guest

Revision ID: 186c0389807f
Revises: a39b750fcf60
Create Date: 2023-04-12 14:29:10.719506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '186c0389807f'
down_revision = 'a39b750fcf60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('occupation', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guests', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('occupation')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
